@targetService = {{host}}/{{editService}}

### Request edit
GRPC {{targetService}}/RequestEdit

{
  "edit": {
    "setAttributeRequest": {
      "node": {
        "nodeId": 3
      },
      "attributeName": "alter",
      "attributeValue": "17"
    }
  }
}